-- Supabase SQL Editor'de bu komutları çalıştırın (tabloları oluşturur)
create table if not exists public.users (
  id bigint generated by default as identity primary key,
  username text unique not null,
  password_hash text not null,
  full_name text
);

create table if not exists public.settings (
  key text primary key,
  value text not null
);

create table if not exists public.apartments (
  id bigint generated by default as identity primary key,
  no integer unique not null,
  owner text default '',
  phone text default '',
  note text default '',
  is_manager integer not null default 0
);

create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  type text not null check (type in ('income','expense')),
  category text not null,
  amount numeric not null,
  description text default '',
  date text not null,
  month text not null,
  apartment_id bigint references public.apartments(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists idx_tx_month on public.transactions(month);
create index if not exists idx_tx_type on public.transactions(type);
